# Stage-1: Build-Stage
FROM node:16.13.2-alpine3.15 	AS build
WORKDIR /app
COPY package.json yarn.lock  ./
RUN yarn install
COPY . .
RUN yarn run build


# Stage-2: Production-Stage
FROM nginx:1.21.6-alpine
RUN addgroup app && adduser -S -G app app
USER app
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
